name: Build and Run Applications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      continue-on-error: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run backend
      working-directory: ./backend
      run: |
        source venv/bin/activate
        python main.py &
      continue-on-error: true

    - name: Run frontend
      working-directory: ./frontend
      run: npm start
      continue-on-error: true

    - name: Report success
      if: ${{ success() }}
      run: echo "Applications are running with errors ignored."
